### PR TITLE
Spanish Vat

### PR DESCRIPTION
**Pull request by braito4**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/GPCsolutions/doliwoo/pull/66%23issuecomment-77533056%22%2C%20%22https%3A//github.com/GPCsolutions/doliwoo/pull/66%23issuecomment-77535792%22%2C%20%22https%3A//github.com/GPCsolutions/doliwoo/pull/66%23issuecomment-77538608%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/GPCsolutions/doliwoo/pull/66%23issuecomment-77533056%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Thanks%20for%20your%20contribution.%5Cr%5CnPlease%20fix%20the%20indentation%20on%20line%2027%20%28See%20Travis%29%20and%20I%27ll%20merge%20it.%22%2C%20%22created_at%22%3A%20%222015-03-06T09%3A50%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1210367%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/rdoursenaud%22%7D%7D%2C%20%7B%22body%22%3A%20%22Done%20%3B%29%22%2C%20%22created_at%22%3A%20%222015-03-06T10%3A12%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1913498%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/braito4%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-03-06T10%3A34%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1210367%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/rdoursenaud%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/rdoursenaud%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1210367%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/rdoursenaud'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/GPCsolutions/doliwoo/pull/66#issuecomment-77533056'>General Comment</a></b>
- <a href='https://github.com/rdoursenaud'></a> Thanks for your contribution.
Please fix the indentation on line 27 (See Travis) and I'll merge it.
- <a href='https://github.com/braito4'></a> Done ;)
- <a href='https://github.com/rdoursenaud'></a> :+1: :shipit:

<a href='https://www.codereviewhub.com/GPCsolutions/doliwoo/pull/66?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/GPCsolutions/doliwoo/pull/66?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/GPCsolutions/doliwoo/pull/66?approve=0'></a>&nbsp;<a href='https://github.com/GPCsolutions/doliwoo/pull/66'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by rdoursenaud** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/GPCsolutions/doliwoo/pull/66'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by rdoursenaud** [comment]
Thanks for your contribution.
Please fix the indentation on line 27 (See Travis) and I'll merge it.

**Comment by braito4** [comment]
Done ;)

**Comment by rdoursenaud** [comment]
:+1: :shipit:

**Comment by rdoursenaud** [comment]
Thanks!

**Pull request merged**
